services:
  web:
    image: keinermendoza/coin-seller:v0.1.0c
    command:
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh
        gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles/:/usr/src/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
  celery:
    image: keinermendoza/coin-seller:v0.1.0c 
    command: celery -A core worker -l info
#    volumes:
#      - ./project/:/usr/src/app/
    env_file:
      - ./.env.prod
    restart: unless-stopped
    depends_on:
      - redis
  celery-beat:
    image: keinermendoza/coin-seller:v0.1.0c
    command: celery -A core beat -l info
#    volumes:
#      - ./project/:/usr/src/app/
    env_file:
      - ./.env.prod
    restart: unless-stopped
    depends_on:
      - redis
