# Generated by Django 5.0.7 on 2025-04-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='currencies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('publisher_name', models.CharField(max_length=100)),
                ('opertarion_type_for_usdt', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
                ('extra_data_listing', models.JSONField()),
                ('extra_data_publisher', models.JSONField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_conditions', to='p2p.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyOperationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_for_buy_usdt', models.JSONField()),
                ('filter_for_sell_usdt', models.JSONField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_preferences', to='p2p.currency')),
            ],
        ),
    ]
