# Generated by Django 5.0.7 on 2025-04-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyoperationpreferences',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_preferences', to='p2p.currency'),
        ),
    ]
