# Generated by Django 5.0.7 on 2025-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_alter_currencyoperationpreferences_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchangeconditions',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='currencyexchangeconditions',
            name='opertarion_type_for_usdt',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, verbose_name='type'),
        ),
    ]
