# Generated by Django 5.0.7 on 2025-04-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_alter_currencyexchangeconditions_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchangeconditions',
            old_name='opertarion_type_for_usdt',
            new_name='operation_type',
        ),
        migrations.CreateModel(
            name='FiatExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('minimum_revenue_expected', models.DecimalField(decimal_places=3, max_digits=8)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_origin', to='p2p.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_destination', to='p2p.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiatExchangePairRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fiat_exchage_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='p2p.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
