# Generated by Django 5.0.7 on 2025-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_rename_minimum_revenue_expected_fiatexchangepair_minimum_margin_expected_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fiatexchangepair',
            constraint=models.UniqueConstraint(fields=('currency_from', 'currency_to'), name='unique_currency_pair_direction'),
        ),
    ]
