# Generated by Django 5.0.7 on 2025-04-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0006_fiatexchangepair_unique_currency_pair_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatexchangepairrate',
            name='fiat_exchage_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='p2p.fiatexchangepair'),
        ),
    ]
