# Generated by Django 5.0.7 on 2025-04-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0007_alter_fiatexchangepairrate_fiat_exchage_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatexchangepairrate',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='fiatexchangepairrate',
            old_name='fiat_exchage_pair',
            new_name='fiat_exchange_pair',
        ),
    ]
