# Generated by Django 5.0.7 on 2025-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0008_alter_fiatexchangepairrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatexchangepair',
            name='maximum_margin_limit',
            field=models.DecimalField(decimal_places=3, default=6.5, max_digits=8),
            preserve_default=False,
        ),
    ]
