# Generated by Django 5.0.7 on 2025-04-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0010_fiatexchangedummypairrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatexchangedummypairrate',
            name='market_rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
