# Generated by Django 5.0.7 on 2025-04-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0011_fiatexchangedummypairrate_market_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatexchangedummypairrate',
            name='max',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiatexchangedummypairrate',
            name='min',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
