# Generated by Django 5.0.7 on 2025-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0012_fiatexchangedummypairrate_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangeconditions',
            name='extra_data_listing',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangeconditions',
            name='extra_data_publisher',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
