# Generated by Django 5.0.7 on 2025-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0013_alter_currencyexchangeconditions_extra_data_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangeconditions',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
