# Generated by Django 5.0.7 on 2025-04-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0014_alter_currencyexchangeconditions_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_currency_exchange_conditions', models.BooleanField(default=False)),
                ('store_fiat_exchange_dummy_pair_rate', models.BooleanField(default=False)),
            ],
        ),
    ]
