# Generated by Django 5.0.7 on 2025-04-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0015_switchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmodel',
            name='email_alert_when_rates_are_out_of_range',
            field=models.BooleanField(default=False),
        ),
    ]
