# Generated by Django 5.0.7 on 2025-04-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0016_switchmodel_email_alert_when_rates_are_out_of_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatexchangedummypairrate',
            name='market_buy_conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dummy_pair_rates_buy', to='p2p.currencyexchangeconditions'),
        ),
        migrations.AddField(
            model_name='fiatexchangedummypairrate',
            name='market_sell_conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dummy_pair_rates_sell', to='p2p.currencyexchangeconditions'),
        ),
        migrations.AddField(
            model_name='fiatexchangepairrate',
            name='market_buy_conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair_rates_buy', to='p2p.currencyexchangeconditions'),
        ),
        migrations.AddField(
            model_name='fiatexchangepairrate',
            name='market_sell_conditions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair_rates_sell', to='p2p.currencyexchangeconditions'),
        ),
    ]
