# Generated by Django 5.0.7 on 2025-04-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0017_fiatexchangedummypairrate_market_buy_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField()),
                ('font_size', models.IntegerField()),
                ('layout', models.JSONField()),
            ],
        ),
    ]
