# Generated by Django 5.0.7 on 2025-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0018_imagecoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecoordinates',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
