# Generated by Django 5.0.7 on 2025-04-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0019_imagecoordinates_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecoordinates',
            name='description',
        ),
        migrations.AddField(
            model_name='imagecoordinates',
            name='name',
            field=models.SlugField(blank=True),
        ),
    ]
