# Generated by Django 5.0.7 on 2025-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0020_remove_imagecoordinates_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatexchangepair',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
