# Generated by Django 5.0.7 on 2025-04-25 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0021_fiatexchangepair_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, help_text='amount of currency traded', max_digits=8)),
                ('price', models.DecimalField(decimal_places=3, help_text='price expresed in the axe asset', max_digits=8)),
                ('side_operation', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Recently opened'), (2, 'One side is ready'), (3, 'Completed'), (4, 'Cancelled')], default=1)),
                ('exchange_buy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_buy', to='p2p.exchange')),
                ('exchange_sell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_sell', to='p2p.exchange')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='p2p.fiatexchangepair')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
