# Generated by Django 5.0.7 on 2025-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0024_traderequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pendiente'), (2, 'Media operación realizada'), (3, 'Dinero entregado al destinatario'), (4, 'Operación cancelada')], default=1),
        ),
    ]
