# Generated by Django 5.0.7 on 2025-05-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0026_traderequest_client_offered_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='amount',
            field=models.DecimalField(decimal_places=3, help_text='amount of currency traded', max_digits=13),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='result',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='amount expressed in destination currency, for example: for VES to BRL result is expressed in BRL', max_digits=8, null=True),
        ),
    ]
