# Generated by Django 5.0.7 on 2025-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0027_alter_exchange_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchmodel',
            name='destroy_old_currency_exchange_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
